In [1]:
%matplotlib inline 
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import matplotlib.pyplot as plt; plt.rcdefaults() 
import pandas.plotting as scatter_matrix 

In [58]:
df = pd.read_csv('C:\\Users\\diyas\\Documents\\Recommendation_system\\vppyh-mao32.csv',skipinitialspace=True) 

In [59]:
#only placed
df = df[df['Placement Status'] == "Placed"]
df=df.drop(['Mobile', 'SRN','Name','Reason','Email','Placement Status','Program'], axis=1)
df = df[df['TierLevel'].notnull()]

In [60]:
df.columns

Index(['Branch', 'CGPA', 'CompanyName', 'CTC', 'TierLevel'], dtype='object')

In [61]:
df.head()

Branch  CGPA CompanyName       CTC  TierLevel
11     BT  7.58       Wipro  650000.0        2.0
12     BT  7.58   Accenture  400000.0        2.0
13     BT  7.58         TCS  368000.0        3.0
53    CSE  8.06   Autoninja  600000.0        2.0
54    CSE  8.06   Autoninja  600000.0        2.0

In [62]:
len(df)

515

In [63]:
df['CompanyName']=df.CompanyName.str.lower()

In [64]:
df.CompanyName.unique()
#df.CompanyName.nunique(dropna = True)

array(['wipro', 'accenture', 'tcs', 'autoninja', 'youplus', 'deloitte',
       'mahindra comviva', 'lam research', 'microsoft', 'akamai ',
       'ugam solutions', 'walmart labs', 'ibm in the cognitive division',
       'sabre', 'oracle ', 'wells fargo', 'goldman sachs', 'logmein',
       'logmein (internship)', 'deloitte india', 'ibm',
       'mentor graphics, internship', 'ivanti', 'onedirect', 'cerner',
       'philips', 'instamojo', 'wissen technology', 'nasdaq', 'citrix',
       'amazon', 'shell technologies', 'societe generale', 'epsilon',
       'cisco systems', 'zscaler', 'ge appliances', 'cisco', 'akamai',
       'hewlett packard enterprise', 'cisco ', 'the math company',
       'mcafee', 'vmware', 'whatfix', 'logmein inc.', 'deloitte usi',
       'vantage agora', 'qualcomm', 'shell india', 'atos ', 'auto ninja',
       'scripbox', 'perfios', 'infibeam', 'couchbase', 'oracle',
       'wipro limited', 'sprinklr', 'microsoft india(r&d) pvt. ltd',
       'zynga', 'hpe', 'edgeverv

In [150]:
#Model 1
#Decision Tree between CGPA,Branch and TierLevel(target)
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO 
from IPython.display import Image 
from pydot import graph_from_dot_data
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree, metrics

In [179]:
#pd.get_dummies(df1['Branch'], prefix='Branch')
df1=df.drop(['CompanyName','CTC'], axis=1)
df1['Branch'],_ = pd.factorize(df1['Branch'])
#df1['TierLevel']=pd.to_numeric(df1['TierLevel'], downcast='integer')

In [180]:
df1.TierLevel.unique()

array([2., 3., 1.])

In [181]:
X = df1.iloc[:,:-1]
y = df1.iloc[:,-1]#Target

In [182]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [185]:
#Entropy
dtree = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=100)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [186]:
y_pred = dtree.predict(X_test)
count_misclassified = (y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))
print("Report : ", 
    classification_report(y_test, y_pred)) 
print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 

Misclassified samples: 35
Accuracy: 0.77
Report :                precision    recall  f1-score   support

         1.0       0.89      0.76      0.82        67
         2.0       0.70      0.92      0.80        75
         3.0       0.00      0.00      0.00        13

    accuracy                           0.77       155
   macro avg       0.53      0.56      0.54       155
weighted avg       0.73      0.77      0.74       155

Confusion Matrix:  [[51 16  0]
 [ 6 69  0]
 [ 0 13  0]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [187]:
#Gini Index
dtree = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=100)
dtree.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [188]:
y_pred = dtree.predict(X_test)
count_misclassified = (y_test != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {:.2f}'.format(accuracy))
print("Report : ", 
    classification_report(y_test, y_pred)) 
print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 

Misclassified samples: 44
Accuracy: 0.72
Report :                precision    recall  f1-score   support

         1.0       0.90      0.67      0.77        67
         2.0       0.66      0.87      0.75        75
         3.0       0.17      0.08      0.11        13

    accuracy                           0.72       155
   macro avg       0.57      0.54      0.54       155
weighted avg       0.72      0.72      0.70       155

Confusion Matrix:  [[45 22  0]
 [ 5 65  5]
 [ 0 12  1]]


In [ ]:
#Entropy based DT is givng us slightly better metrics
#This is a basic model based on the available data